import "./globals.css";

// import Head from 'next/head'

export const metadata = {
  title: "Form-Xolo",
  description: "Generated by create next app",
  charset:"UTF-8",
};

// H1
// Metadata
// Arreglar textos a ingles
// Avisar error de firma
// Estado de guardar
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-overlay">
        <div className=" relative min-h-screen flex flex-col items-center mt-12">
          {children}
        </div>
      </body>
    </html>
  );
}
